/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_scheffers_robot_emu_GR8EMUr3_1_EmuThread */

#ifndef _Included_net_scheffers_robot_emu_GR8EMUr3_1_EmuThread
#define _Included_net_scheffers_robot_emu_GR8EMUr3_1_EmuThread
#ifdef __cplusplus
extern "C" {
#endif
#undef net_scheffers_robot_emu_GR8EMUr3_1_EmuThread_MIN_PRIORITY
#define net_scheffers_robot_emu_GR8EMUr3_1_EmuThread_MIN_PRIORITY 1L
#undef net_scheffers_robot_emu_GR8EMUr3_1_EmuThread_NORM_PRIORITY
#define net_scheffers_robot_emu_GR8EMUr3_1_EmuThread_NORM_PRIORITY 5L
#undef net_scheffers_robot_emu_GR8EMUr3_1_EmuThread_MAX_PRIORITY
#define net_scheffers_robot_emu_GR8EMUr3_1_EmuThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
