/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_scheffers_robot_emu_GR8CPURev3_1 */

#ifndef _Included_net_scheffers_robot_emu_GR8CPURev3_1
#define _Included_net_scheffers_robot_emu_GR8CPURev3_1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_scheffers_robot_emu_GR8CPURev3_1
 * Method:    nativeTick
 * Signature: (I)II
 */
JNIEXPORT jint JNICALL Java_net_scheffers_robot_emu_GR8CPURev3_11_nativeTick
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
