/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_scheffers_robot_emu_GR8EMUr3_1 */

#ifndef _Included_net_scheffers_robot_emu_GR8EMUr3_1
#define _Included_net_scheffers_robot_emu_GR8EMUr3_1
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
